# fly.toml app configuration file generated for productinsightai-backend
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "productinsightai-backend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  APP_NAME = "ProductInsightAI Backend"
  DEBUG = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 2
  max_machines_running = 4
  processes = ["app"]

  # Autoscaling configuration
  [http_service.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 80

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"

[deploy]
  strategy = "rolling"

[metrics]
  port = 8000
  path = "/api/health"

# Mount volume for persistent assets storage
[[mounts]]
  source = "assets_data"
  destination = "/app/attached_assets"
